schedule:
  server:
    transport:
      config:
        serverPort: 9008
    register:
      code: eureka
      serverList:
        - http://127.0.0.1:2001/eureka/
      eurekaConfig:
        registerSelf: true
    task:
      notifyType: DB
      dataSource:
        url: N6q9ztoNQe838nXLWS6T9G0vRZbdidBTmfHyJ2tCBsFIFcboMr+jalsmq/hgTCzA1noUg47DaDuv2u4E7Yw6Drzoc9EUfVkLJCk6HII0F4G5vJq9QY3IZMuICMWienEr1ORS4rN2IMw=
        userName: xEIL5dpjPsItpep2+NTptg==
        password: xEIL5dpjPsItpep2+NTptg==
      messageConfig:
        useKerberos: false
      groupList:
        - "101"

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
